

def problem_1():
    """If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. 
    The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000."""
    sum_of_nums = 0
    for number in range(1000):
        if number % 3 == 0 or number % 5 == 0:
            sum_of_nums += number
    return sum_of_nums

#print(problem_1())
        
def problem_2():
    """Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    find the sum of the even-valued terms."""
    fibonacci_sequence = [1, 2]
    sum_of_nums = 0
    for num in fibonacci_sequence:
        #create array with Fibonacci sequence
        fib_sum = fibonacci_sequence[-1] + fibonacci_sequence[-2]
        if (fib_sum > 4000000):
            break
        fibonacci_sequence.append(fib_sum)
        
    for number in fibonacci_sequence:
        if number % 2 == 0:
            sum_of_nums += number
    
    return sum_of_nums

#print(problem_2())








